project:
  type: website

website:
  title: "Something Simply Stochastic"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: posts.qmd
        text: Posts
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo

